### ISSUE TITLE
Debugging of x64 assembly stops with error

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1004]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

1-2 weeks CI build used

- What version did you use?
5.x.x shown in ABout

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Got this (sporadic) error during debugging of 64 bit exe (it's not 100% reproducible), maybe stack trace will tell smth to author

```
---------------------------
dnSpy
---------------------------
System.Windows.Markup.XamlParseException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)

   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority)

   at dnSpy.Debugger.DotNet.Evaluation.Engine.DbgDotNetDispatcherExtensions.InvokeRethrow[T](DbgDotNetDispatcher dispatcher, Func`1 callback)

   at dnSpy.Debugger.DotNet.Evaluation.Engine.DbgEngineValueNodeImpl.Format(DbgEvaluationInfo evalInfo, IDbgValueNodeFormatParameters options, CultureInfo cultureInfo) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger.DotNet\Evaluation\Engine\DbgEngineValueNodeImpl.cs:line 112

   at dnSpy.Debugger.Evaluation.ViewModel.Impl.ValueNodeImpl.InitializeCachedText() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Evaluation\ViewModel\Impl\ValueNodeImpl.cs:line 105

   at dnSpy.Debugger.Evaluation.ViewModel.Impl.ValueNodeImpl.get_CachedName() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Evaluation\ViewModel\Impl\ValueNodeImpl.cs:line 66

   at dnSpy.Debugger.Evaluation.UI.VariablesWindowColumnConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Evaluation\UI\VariablesWindowColumnConverter.cs:line 43

   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)

   at System.Windows.Data.BindingExpression.Activate(Object item)

   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)

   at System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)

   at System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)

   at System.Windows.StyleHelper.GetInstanceValue(UncommonField`1 dataField, DependencyObject container, FrameworkElement feChild, FrameworkContentElement fceChild, Int32 childIndex, DependencyProperty dp, Int32 i, EffectiveValueEntry& entry)

   at System.Windows.FrameworkTemplate.ReceivePropertySet(Object targetObject, XamlMember member, Object value, DependencyObject templatedParent)

   at System.Windows.FrameworkTemplate.<>c__DisplayClass45_0.<LoadOptimizedTemplateContent>b__3(Object sender, XamlSetValueEventArgs setArgs)

   at System.Xaml.XamlObjectWriter.OnSetValue(Object eventSender, XamlMember member, Object value)

   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent)

   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)

   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)

   at System.Xaml.XamlObjectWriter.WriteEndObject()

   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)

   --- End of inner exception stack trace ---

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)

   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)

   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)

   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)

   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)

   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)

   at System.Windows.FrameworkElement.ApplyTemplate()

   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)

   at System.Windows.UIElement.Measure(Size availableSize)

   at System.Windows.Controls.GridViewRowPresenter.MeasureOverride(Size constraint)

   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)

   at System.Windows.UIElement.Measure(Size availableSize)

   at System.Windows.Controls.Border.MeasureOverride(Size constraint)

   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)

   at System.Windows.UIElement.Measure(Size availableSize)

   at System.Windows.Controls.Control.MeasureOverride(Size constraint)

   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)

   at System.Windows.UIElement.Measure(Size availableSize)

   at System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Double& computedUniformOrAverageContainerPixelSize, Boolean& computedAreContainersUniformlySized, Boolean& hasAnyContainerSpanChanged, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)

   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)

   at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)

   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)

   at System.Windows.UIElement.Measure(Size availableSize)

   at System.Windows.ContextLayoutManager.UpdateLayout()

   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)

   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

![screenshot_26](https://user-images.githubusercontent.com/765343/49135563-ba35e580-f2ef-11e8-9d20-a4a68846db66.png)

Note: after this error debugging stops.

**Comment by greenozon** [comment]
Well, if you know the exact code-flow that lead to this error - great!
I propose to handle it, as once process exited (I bet that was my case!)   - nothing to debug, right? :)
