### ISSUE TITLE
Export to project failed:  Cannot replace the root node

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1086]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
dnSpy v6.0.3 (.NET Framework)

dnSpy is licensed under GPLv3.

- Write down all steps needed to reproduce this issue. Also attach any needed files.

export file to project, got 2 times same error:

File creation failed (c:\-----PluginHostForm.cs), description = Create WinForms file, Exception message: Cannot replace the root node

if you navigate to that class following error printed out:

```
An error occurred
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Cannot replace the root node
   at ICSharpCode.NRefactory.CSharp.AstNode.ReplaceWith(AstNode newNode) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\AstNode.cs:line 541
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 102
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 236
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 29
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 66
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 57
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 187
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Cannot replace the root node
   at ICSharpCode.NRefactory.CSharp.AstNode.ReplaceWith(AstNode newNode) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\AstNode.cs:line 541
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 102
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 236
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 29
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 66
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 57
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 187
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

https://www.sendspace.com/file/65raun

**Comment by xsilent007** [comment]
@greenozon Can you reupload the file? It seems to be down...

**Comment by greenozon** [comment]
well, that's a very good question...
can't find it after 1 month, sorry

if the stack trace info is not enough, then I guess its reasonable to close it?

**Comment by xsilent007** [comment]
The stack trace on its own is not really enough, sadly...

**Comment by 0xd4d** [comment]
> if the stack trace info is not enough, then I guess its reasonable to close it?

Let me know if you find it.
