### ISSUE TITLE
NullReferenceException when view IL of an edited method without reload

### ISSUE THREAD

**Issue by yyjdelete** [0xd4d/dnSpy#1165]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
6.0.5(CI builds)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Try edit any method with C#, add the below code, and compile.
2. Switch to IL view without save and reload.
(It works well after save modules and reload.)
```cs
var dic = new System.Collections.Generic.Dictionary<int, int>();
dic.TryGetValue(0, out var tmp);
```
3. See an NullReferenceException
```cs
System.NullReferenceException: The object reference was not set to an instance of the object.
   at dnlib.DotNet.TypeDefMD.InitializeGenericParameters()
   at dnlib.DotNet.TypeDef.get_GenericParameters()
   at dnlib.DotNet.GenericSig.get_GenericParam()
   at dnlib.DotNet.FullNameFactory.CreateTypeSigName(TypeSig typeSig, Int32 flags)
   at dnlib.DotNet.FullNameFactory.NameSB(TypeSig typeSig, Boolean isReflection, StringBuilder sb)
   at ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(TypeSig type, IDecompilerOutput writer, ILNameSyntax syntax, Int32 depth) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\DisassemblerHelpers.cs:line 484
   at ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.Write(IDecompilerOutput writer, MethodSig sig, IMethod method) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\DisassemblerHelpers.cs:line 315
   at ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteOperand(IDecompilerOutput writer, Object operand, Int32 maxStringLength, MethodDef method) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\DisassemblerHelpers.cs:line 663
   at ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(Instruction instruction, IDecompilerOutput writer, DisassemblerOptions options, UInt32 baseRva, Int64 baseOffs, IInstructionBytesReader byteReader, MethodDef method, InstructionOperandConverter instructionOperandConverter, PdbAsyncMethodCustomDebugInfo pdbAsyncInfo, Int32& startLocation) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\DisassemblerHelpers.cs:line 199
   at ICSharpCode.Decompiler.Disassembler.MethodBodyDisassembler.WriteStructureBody(CilBody body, ILStructure s, HashSet`1 branchTargets, Int32& index, MethodDebugInfoBuilder builder, InstructionOperandConverter instructionOperandConverter, Int32 codeSize, UInt32 baseRva, Int64 baseOffs, IInstructionBytesReader byteReader, PdbAsyncMethodCustomDebugInfo pdbAsyncInfo, MethodDef method) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\MethodBodyDisassembler.cs:line 237
   at ICSharpCode.Decompiler.Disassembler.MethodBodyDisassembler.Disassemble(MethodDef method, MethodDebugInfoBuilder builder, InstructionOperandConverter instructionOperandConverter) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\MethodBodyDisassembler.cs:line 114
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleMethodInternal(MethodDef method, Boolean addLineSep, Int32 methodStartPosition) // C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Disassembler\ReflectionDisassembler.cs:line 409
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) // C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 28
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) // C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 66
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) // C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 61
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) // C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 220
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

**Comment by 0xd4d** [comment]
The latest build should have the fix.
