### ISSUE TITLE
Inconsistent Stacksize error

### ISSUE THREAD

**Issue by CarlSchou** [0xd4d/dnSpy#124]
Some functions in a dll i'm reversing makes dnSpy shit itself.
I've been able to replicate this issue by using ConfuserEx (v6) with very heavy cflow, only happens sometimes and not on all functions (same in dll)

> /*
An exception occurred when decompiling this method (06000018)
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.String[] ns0.Class0::smethod_11(System.String,System.Char)
 ---> System.Exception: Inconsistent stack size at IL_26
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MemberMapping& mm)
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, StringBuilder sb, MemberMapping& mm)
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, StringBuilder sb, MemberMapping& mm)
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethodBody(MethodDef method, IEnumerable`1 parameters, MemberMapping& mm)
*/

**Comment by CarlSchou** [comment]
I can view the IL code just fine btw

**Comment by 0xd4d** [comment]
You should try to deobfuscate the obfuscated code first. Even if I'd fix this case, the code would probably be too difficult to understand anyway, and you'd have to fix the control flow to understand it.
