### ISSUE TITLE
[Error] Arithmetic Operation resulted in Overflow

### ISSUE THREAD

**Issue by AxDSan** [0xd4d/dnSpy#125]
Whenever I try to see a method's body, It throws this Overflow error:

```
/*
An exception occurred when decompiling this method (060004D5)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void wb::a()
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition) in C:\projects\dnspy\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 48
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in C:\projects\dnspy\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 373
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context) in C:\projects\dnspy\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 264
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MemberMapping& mm) in C:\projects\dnspy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 101
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, StringBuilder sb, MemberMapping& mm) in C:\projects\dnspy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 79
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, StringBuilder sb, MemberMapping& mm) in C:\projects\dnspy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 83
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethodBody(MethodDef method, IEnumerable`1 parameters, MemberMapping& mm) in C:\projects\dnspy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1276
*/
```

Trying to reload the method's body doesn't solve this problem. When I try to see IL Code I can see the structure just fine, however the method's body I want to analyze is not there. Reloading doesn't seems to do any difference.

**Comment by 0xd4d** [comment]
It's probably obfuscated. You can try to deobfuscate it first. Even if it managed to show you some code, it'd probably be too difficult to understand it.

**Comment by AxDSan** [comment]
Got it xD again thanks for replying.

**Comment by XenocodeRCE** [comment]
Can you provide sample please ? @AxDSan

**Comment by AxDSan** [comment]
@XenocodeRCE No, sorry!
