### ISSUE TITLE
WPF does not work for extensions in different folders NET472

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#1533]
When putting extensions in `bin/Extensions/MyExt/` or when using the `--extension-directory` flag on the .NET Framework version of dnSpy, WPF components (such as a settings pane or custom dialog window) won't get loaded and cause an exception to pop up. Dependencies do get loaded correctly, though.

When using .NET Core, everything works as expected.

```
System.IO.FileNotFoundException: Could not load file or assembly 'dnSpy.Extension.HoLLy.x, Version=0.3.0, Culture=neutral' or one of its dependencies. The system cannot find the file specified.

File name: 'dnSpy.Extension.HoLLy.x, Version=0.3.0, Culture=neutral'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at HoLLy.dnSpyExtension.PluginSettings.SettingsControl.InitializeComponent()
   at HoLLy.dnSpyExtension.PluginSettings.SettingsPage.get_UIObject()
   at dnSpy.Settings.Dialog.ShowAppSettingsDialog.dnSpy.Settings.Dialog.IPageUIObjectLoader.GetUIObject(AppSettingsPage page) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Settings\Dialog\ShowAppSettingsDialog.cs:line 96
   at dnSpy.Settings.Dialog.AppSettingsPageVM.GetOrCreatePageAndUIObject() in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Settings\Dialog\AppSettingsPageVM.cs:line 79
   at dnSpy.Settings.Dialog.AppSettingsPageVM.get_VisiblePageAndUIObject() in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Settings\Dialog\AppSettingsPageVM.cs:line 47
   at dnSpy.Settings.Dialog.ShowAppSettingsDialog.Show(Nullable`1 guid, Window ownerWindow) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Settings\Dialog\ShowAppSettingsDialog.cs:line 141
   at dnSpy.Settings.Dialog.AppSettingsService.Show2(Nullable`1 guid, Window owner) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Settings\Dialog\AppSettingsService.cs:line 79
   at dnSpy.Settings.Dialog.AppSettingsService.Show(Guid guid, Window owner) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Settings\Dialog\AppSettingsService.cs:line 69
   at HoLLy.dnSpyExtension.SourceMap.Commands.OpenSettings.Execute(IMenuItemContext context)
   at dnSpy.Menus.MenuService.<>c__DisplayClass15_0.<Create>b__1(Object a) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Menus\MenuService.cs:line 345
   at dnSpy.Contracts.MVVM.RelayCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy.Contracts.DnSpy\MVVM\RelayCommand.cs:line 49
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by 0xd4d** [comment]
Sounds like we need to install an assembly resolver. The .NET Core build already has one.
