### ISSUE TITLE
When a memory only module is loaded, dnSpy's search breaks

### ISSUE THREAD

**Issue by MulleDK19** [0xd4d/dnSpy#1561]
Tested on latest v6.1.7.

If an assembly has been loaded from memory, it's impossible to search.

IE. Assembly.Load(byte[])
When an assembly like this is loaded into dnSpy, the search feature throws an exception:
```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at dnSpy.Search.FrameworkFileUtils.IsFrameworkAssembly(String filename, String assemblySimpleName) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Search\FrameworkFileUtils.cs:line 460
   at dnSpy.Search.SearchControlVM.CanSearchFile(DsDocumentNode node) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Search\SearchControlVM.cs:line 228
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at dnSpy.Search.DocumentSearcher.Start(IEnumerable`1 files) in D:\a\dnSpy\dnSpy\dnSpy\dnSpy\Search\DocumentSearcher.cs:line 91
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Steps to reproduce:
1. Debug an assembly that loads another assembly via a byte array (Assembly.Load(byte[]))
2. Open Debug > Modules
3. Right click the list > Open all modules
4. Try to search.

Attached test case.
Step over the Assembly.Load() call, then continue at step 2.

**Comment by MulleDK19** [comment]
[TestCase.zip](https://github.com/0xd4d/dnSpy/files/5122374/TestCase.zip)

**Comment by 0xd4d** [comment]
Do you want to send a PR?
