### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by lanzhiquan** [0xd4d/dnSpy#1580]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
2020-9-16 commit e349f76 #1579 

- Write down all steps needed to reproduce this issue. Also attach any needed files.
<img width="1039" alt="2020-09-16_090913" src="https://user-images.githubusercontent.com/11311878/93280878-50a50500-f7fd-11ea-9431-e646da87fbf7.png">

**Comment by andrew-boyarshin** [comment]
I am experiencing the same issue. Deleting `AppData\Local\dnSpy\Startup64\netcore` (for dnspy-netcore-win64) doesn't help. 6.1.7 stable release works.

**Comment by Deltafox79** [comment]
confirm isssue also delete all dnspy directory on %appdata%/Local and Roaming..

**Comment by rickbrew** [comment]
Same here. Running Win10 v2004. Happens whether I choose Light or Dark theme in Windows Settings.

**Comment by rickbrew** [comment]
If I run a debug build, I get this error for the first theme it tries to load. None of the themes successfully load though.

![image](https://user-images.githubusercontent.com/10873410/93811028-6010bd80-fc04-11ea-99c4-83b19ef7f1dd.png)

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Missing info: SearchBoxWatermark



   at dnSpy.Themes.Theme..cctor() in D:\src\github\dnSpy\dnSpy\dnSpy\Themes\Theme.cs:line 66

   at dnSpy.Themes.Theme..ctor(XElement root)

   at dnSpy.Themes.ThemeService.Load(String filename) in D:\src\github\dnSpy\dnSpy\dnSpy\Themes\ThemeService.cs:line 173

   at dnSpy.Themes.ThemeService.Load() in D:\src\github\dnSpy\dnSpy\dnSpy\Themes\ThemeService.cs:line 161

   at dnSpy.Themes.ThemeService..ctor(ThemeSettings themeSettings) in D:\src\github\dnSpy\dnSpy\dnSpy\Themes\ThemeService.cs:line 111

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod, Object[] arguments)

   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePa......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by rickbrew** [comment]
Thanks @0xd4d , it works now!
