### ISSUE TITLE
Not able to publish SCD for master branch

### ISSUE THREAD

**Issue by jiangzeng01** [0xd4d/dnSpy#1584]
Hi 

I'm trying to publish SCD app for the master branch, published successfully but failed to launch.
Published with:
`dotnet publish dnSpy.csproj -r win-x64 --self-contained true --framework netcoreapp3.1`

I saw you published a SCD version, it would be great that if you can share how to publish SCD with master branch?

SCD app launched failed with:
```
Microsoft.VisualStudio.Composition.CompositionFailedException: Errors exist in the composition.
   at Microsoft.VisualStudio.Composition.CompositionConfiguration.ThrowOnErrors()
   at dnSpy.MainApp.App.CreateExportProviderFactorySlow(Resolver resolver) in D:\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 202
   at dnSpy.MainApp.App.InitializeMEF(Boolean readSettings, Boolean useCache) in D:\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 127
   at dnSpy.MainApp.App.<>c__DisplayClass15_0.<.ctor>b__0() in D:\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 102
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at dnSpy.MainApp.App.OnStartup(StartupEventArgs e) in D:\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 526
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Thanks,
Kevin

**Comment by 0xd4d** [comment]
The CI uses `build.ps1` to build and publish it.

https://github.com/0xd4d/dnSpy/blob/4aaccb6c5bc1d58656b783e79082342dbf59b28f/build.ps1#L39-L68

**Comment by 0xd4d** [comment]
Also have a look at build.yml which calls `build.ps1`: https://github.com/0xd4d/dnSpy/blob/master/.github/workflows/build.yml

**Comment by jiangzeng01** [comment]
@0xd4d Thanks, it works for me.
`powershell.exe ./build.ps1 -buildtfm core-x64 -NoMsbuild`
