### ISSUE TITLE
Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by noone2407** [0xd4d/dnSpy#172]
I have an obfucated exe that have this kind of error when I try to open
When I save to new file or deobfucate it by de4dot 3.1 the new exe fails to run

`		/*
An exception occurred when decompiling this method (060000C7)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void )X+/]l(7@@HAoU;oT+dRN,CX"::.ctor()
 ---> System.OverflowException: Array dimensions exceeded supported range.
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 48
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 373
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 264
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 105
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 83
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 87
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethodBody(MethodDef method, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, MethodKind methodKind, MethodDebugInfoBuilder& builder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1343
*/;`

**Comment by 0xd4d** [comment]
Could be garbage code that needs to be decrypted. What does the IL look like?

**Comment by SlowLogicBoy** [comment]
I get the same error when I try to debug koi (ConfuserEx 0.6.0) module which is in memory, UNKNOWN1 = 0x100
![2016-08-26 13_38_15-server gudjonis lt_3214 - remote desktop connection](https://cloud.githubusercontent.com/assets/3121637/18002757/63c84d3c-6b92-11e6-8a61-f132f4040ad1.png)
![2016-08-26 13_39_28-server gudjonis lt_3214 - remote desktop connection](https://cloud.githubusercontent.com/assets/3121637/18002773/8a1e6f48-6b92-11e6-93e9-13f54dada7f0.png)

**Comment by TiberiumPY** [comment]
SlowLogicBoy - did you tried to use de4dot?

**Comment by SlowLogicBoy** [comment]
I can't when module is in memory ^^, only if I save it in file.

**Comment by 0xd4d** [comment]
It's probably encrypted data. The decompiler only sees garbage: garbage in garbage out. Set a BP right after the data has been decrypted then save it to disk (Modules window -> Save Module command). You can also tell dnSpy to load the module from memory (see the Modules window again), and you should do it after it's been decrypted.

**Comment by SlowLogicBoy** [comment]
That's what I do, however since module that I load from memory belogs to the same assembly dnlib throws exception 
throw new InvalidOperationException("Module already has an assembly. Remove it from that assembly before adding it to this assembly."); in void IListListener<ModuleDef>.OnAdd(int index, ModuleDef module)

But I just move debugger to another location and I can see modules from memory
