### ISSUE TITLE
Modules stay open even after being removed

### ISSUE THREAD

**Issue by saneki** [0xd4d/dnSpy#18]
To replicate:
- Run `de4dot Program.exe`
- Open Program-cleaned.exe in dnSpy
- Close Program-cleaned.exe in dnSpy
- Run `de4dot Program.exe` again
- Throws an exception when trying to write to Program-cleaned.exe:

```
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   The requested operation cannot be performed on a file with a user-mapped section open.
ERROR:
ERROR: Type:
ERROR:   System.IO.IOException
ERROR: ------------------------------------------------------------------------------
```

This also happens for other programs when they try writing to the filepath of an assembly that was opened in dnSpy. Restarting dnSpy is a solution, but not very convenient.

Larger error message:

```
Saving c:\Users\saneki\Git\dnlib-examples\GenericExample3-cleaned.exe
ERROR:
ERROR:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
ERROR:    at System.IO.FileStream.SetLengthCore(Int64 value)
ERROR:    at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName) in c:\Users\saneki\Git\de4dot\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 467
ERROR:    at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options) in c:\Users\saneki\Git\de4dot\dnlib\src\DotNet\ModuleDef.cs:line 1000
ERROR:    at de4dot.code.AssemblyModule.Save(String newFilename, MetaDataFlags mdFlags, IModuleWriterListener writerListener) in c:\Users\saneki\Git\de4dot\de4dot.code\AssemblyModule.cs:line 59
ERROR:    at de4dot.code.ObfuscatedFile.Save() in c:\Users\saneki\Git\de4dot\de4dot.code\ObfuscatedFile.cs:line 341
ERROR:    at de4dot.cui.FilesDeobfuscator.SaveAllFiles(IEnumerable`1 allFiles) in c:\Users\saneki\Git\de4dot\de4dot.cui\FilesDeobfuscator.cs:line 385
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAll() in c:\Users\saneki\Git\de4dot\de4dot.cui\FilesDeobfuscator.cs:line 136
ERROR:    at de4dot.cui.FilesDeobfuscator.DoIt() in c:\Users\saneki\Git\de4dot\de4dot.cui\FilesDeobfuscator.cs:line 91
ERROR:    at de4dot.cui.Program.Main(String[] args) in c:\Users\saneki\Git\de4dot\de4dot.cui\Program.cs:line 117
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   The requested operation cannot be performed on a file with a user-mapped section open.
ERROR:
ERROR: Type:
ERROR:   System.IO.IOException
ERROR: ------------------------------------------------------------------------------
ERROR:
ERROR: Try the latest version!
```

**Comment by 0xd4d** [comment]
Have you tried the latest build? I added a commit about a week ago that fixed a bug that could possibly be what you're seeing here.

**Comment by saneki** [comment]
Pulled latest dnSpy and de4dot and tried again after rebuilding, still occurs.

de4dot commit: 828a1ab398e78c2ede2eb38c0b21bdfd1684c3f4
dnSpy commit: 591b5df7f8dc68b5fbfc3ecb0a4f7efa83705ca9

**Comment by 0xd4d** [comment]
I could reproduce this in XP, not on Win10. There was a memory reference from some internal WPF data structure to the removed treenode

```
  00c5e9a0(ICSharpCode.ILSpy.MainWindow)->
  00df8d8c(ICSharpCode.TreeView.SharpTreeView)->
  0129c480(System.Windows.EffectiveValueEntry[])->
  013cf230(System.Windows.ModifiedValue)->
  012b0ddc(ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode)->
  012ac384(ICSharpCode.ILSpy.LoadedAssembly)->
  012ac3a4(System.Threading.Tasks.Task`1[[dnlib.DotNet.ModuleDef, dnlib]])->
  012aef24(dnlib.DotNet.ModuleDefMD)
```

Reopen this issue if it doesn't fix your problem. You didn't say what OS and .NET runtime you were using.
