### ISSUE TITLE
Error when debugging from memory and another module is loaded.

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#211]
```
System.InvalidOperationException: Module already has an assembly. Remove it from that assembly before adding it to this assembly.
   at dnlib.DotNet.AssemblyDef.dnlib.Utils.IListListener<dnlib.DotNet.ModuleDef>.OnAdd(Int32 index, ModuleDef module) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\AssemblyDef.cs:line 754
   at dnlib.Utils.LazyList`1.Add_NoLock(TValue item) in C:\projects\dnspy\Libraries\dnlib\src\Utils\LazyList.cs:line 384
   at dnlib.Utils.LazyList`1.Add(TValue item) in C:\projects\dnspy\Libraries\dnlib\src\Utils\LazyList.cs:line 374
   at dnSpy.Debugger.IMModules.InMemoryModuleManager.OnModuleAdded(DnModule module) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\IMModules\InMemoryModuleManager.cs:line 127
   at dnSpy.Debugger.IMModules.InMemoryModuleManager.DnDebugger_OnModuleAdded(Object sender, ModuleDebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\IMModules\InMemoryModuleManager.cs:line 116
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at dndbg.Engine.DnDebugger.CallOnModuleAdded(DnModule module, Boolean added) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 90
   at dndbg.Engine.DnDebugger.HandleManagedCallback(DebugCallbackEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 790
   at dndbg.Engine.DnDebugger.OnManagedCallbackInDebuggerThread(DebugCallbackEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 265
   at dndbg.Engine.DnDebugger.<>c__DisplayClass65_1.<OnManagedCallbackFromAnyThread2>b__0() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 229
   at dnSpy.Debugger.WpfDebugMessageDispatcher.EmptyQueue() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\WpfDebugMessageDispatcher.cs:line 65
   at dnSpy.Debugger.WpfDebugMessageDispatcher.<ExecuteAsync>b__7_0() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\WpfDebugMessageDispatcher.cs:line 52
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

To reproduce: Obfuscate assembly with ConfuserEx with Maximum settings and Compression.
The error occurs when dnSpy tries to add koi module to assembly which has an original module in it (Also loaded from memory).

To prevent that I debug dnspy and just skip that throw in dnlib and then I can work normaly.
[This](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/AssemblyDef.cs#L754) is where it throws up

**Comment by SlowLogicBoy** [comment]
Thanks a lot
