### ISSUE TITLE
NullReferenceException during attaching to a process

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#233]
During attach to debug some x64 .NET process dnSpy  raised this huge error box:

```
---------------------------
dnSpy
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at dnSpy.Debugger.Logger.OutputLogger.TheDebugger_OnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Logger\OutputLogger.cs:line 79

   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   at dnSpy.Debugger.TheDebugger.CallOnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 116

   at dnSpy.Debugger.TheDebugger.DnDebugger_OnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 139

   at dndbg.Engine.DnDebugger.ProcessesTerminated() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 1034

   at dndbg.Engine.DnDebugger.HandleManagedCallback(DebugCallbackEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 755

   at dndbg.Engine.DnDebugger.OnManagedCallbackInDebuggerThread(DebugCallbackEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 265

   at dndbg.Engine.DnDebugger.<>c__DisplayClass64_0.<OnManagedCallbackFromAnyThread>b__0() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 212

   at dnSpy.Debugger.WpfDebugMessageDispatcher.EmptyQueue() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\WpfDebugMessageDispatcher.cs:line 64

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

after clicking OK new big error was shown:

```
---------------------------
dnSpy
---------------------------
System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at dnSpy.Debugger.Logger.OutputLogger.DebugState..ctor(DnDebugger dbg) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Logger\OutputLogger.cs:line 99

   at dnSpy.Debugger.Logger.OutputLogger.TheDebugger_OnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Logger\OutputLogger.cs:line 64

   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   at dnSpy.Debugger.TheDebugger.CallOnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 119

   at dnSpy.Debugger.TheDebugger.Initialize(DnDebugger newDebugger) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 105

   at dnSpy.Debugger.DebugManager.Attach(AttachProcessOptions options, String& errMsg) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\DebugManager.cs:line 820

   at dnSpy.Debugger.DebugManager.Attach() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\DebugManager.cs:line 788

   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)

   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)

   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)

   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)

   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)

   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)

   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

version used: dnSpy 3.0.0-beta (one of the latest from appVeyor service)

**Comment by 0xd4d** [comment]
What's the timestamp or git SHA-1 hash of the build? The line numbers don't look 100% correct.

Do you have repro steps?

**Comment by greenozon** [comment]
The timestamp of all the files I"m using are 09/25/2016 11:22
Idea: add git hash into about window for detailed build tracking
http://prntscr.com/crmi0j

I"ll try to repeat the issue on the latest build from appveyor  (x.x.281)

**Comment by greenozon** [comment]
Here are the lines on the latest build (downloaded today), ts = 10/05/2016 17:34

```
---------------------------
dnSpy
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at dnSpy.Debugger.Logger.OutputLogger.TheDebugger_OnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Logger\OutputLogger.cs:line 79

   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   at dnSpy.Debugger.TheDebugger.CallOnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 116

   at dnSpy.Debugger.TheDebugger.DnDebugger_OnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 139

   at dndbg.Engine.DnDebugger.ProcessesTerminated() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 1034

   at dndbg.Engine.DnDebugger.HandleManagedCallback(DebugCallbackEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 755

   at dndbg.Engine.DnDebugger.OnManagedCallbackInDebuggerThread(DebugCallbackEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 265

   at dndbg.Engine.DnDebugger.<>c__DisplayClass64_0.<OnManagedCallbackFromAnyThread>b__0() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dndbg\Engine\DnDebugger.cs:line 212

   at dnSpy.Debugger.WpfDebugMessageDispatcher.EmptyQueue() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\WpfDebugMessageDispatcher.cs:line 64

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```


and 2nd dialog:
```


---------------------------
dnSpy
---------------------------
System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at dnSpy.Debugger.Logger.OutputLogger.DebugState..ctor(DnDebugger dbg) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Logger\OutputLogger.cs:line 99

   at dnSpy.Debugger.Logger.OutputLogger.TheDebugger_OnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Logger\OutputLogger.cs:line 64

   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   at dnSpy.Debugger.TheDebugger.CallOnProcessStateChanged(Object sender, DebuggerEventArgs e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 119

   at dnSpy.Debugger.TheDebugger.Initialize(DnDebugger newDebugger) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\TheDebugger.cs:line 105

   at dnSpy.Debugger.DebugService.Attach(AttachProcessOptions options, String& errMsg) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\DebugService.cs:line 820

   at dnSpy.Debugger.DebugService.Attach() in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\DebugService.cs:line 788

   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)

   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)

   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)

   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)

   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)

   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)

   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

**Comment by 0xd4d** [comment]
Do you have repro steps?

**Comment by 0xd4d** [comment]
Closed, can't repro.

**Comment by greenozon** [comment]
Hi
here are the steps
get the package, unpack, run testDemo.exe,  attach using dnSpy, app will crash, dnSpy will crash
https://www.sendspace.com/file/625lwz

**Comment by greenozon** [comment]
don't know how to reopen this issue..... should I open up new one?

**Comment by 0xd4d** [comment]
Reopened
