### ISSUE TITLE
decompiler error

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#245]
An error occurred
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderExceptionFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.Convert(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at System.Text.DecoderNLS.Convert(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.LinePositionMapper.GetPositionForLine(Int32 line) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 277
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List`1 indexList) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 298
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 241
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider..ctor(String fileName) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 145
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.Create(String fileName) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 117
   at dnSpy.Shared.Languages.XmlDoc.XmlDocLoader.LoadDocumentation(ModuleDef module) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocLoader.cs:line 57
   at dnSpy.Languages.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node) in C:\projects\dnspy\dnSpy.Languages.ILSpy\XmlDoc\AddXmlDocTransform.cs:line 39
   at dnSpy.Languages.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node) in C:\projects\dnspy\dnSpy.Languages.ILSpy\XmlDoc\AddXmlDocTransform.cs:line 51
   at dnSpy.Languages.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node) in C:\projects\dnspy\dnSpy.Languages.ILSpy\XmlDoc\AddXmlDocTransform.cs:line 51
   at dnSpy.Languages.ILSpy.CSharp.CSharpLanguage.AddXmlDocumentation(BuilderState& state, DecompilerSettings settings, AstBuilder astBuilder) in C:\projects\dnspy\dnSpy.Languages.ILSpy\CSharp\CSharpLanguage.cs:line 300
   at dnSpy.Languages.ILSpy.CSharp.CSharpLanguage.Decompile(TypeDef type, ITextOutput output, DecompilationContext ctx) in C:\projects\dnspy\dnSpy.Languages.ILSpy\CSharp\CSharpLanguage.cs:line 280
   at dnSpy.Files.Tabs.NodeDecompiler.Decompile(IFileTreeNodeData node) in C:\projects\dnspy\dnSpy\Files\Tabs\NodeDecompiler.cs:line 92
   at dnSpy.Files.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, IFileTreeNodeData node) in C:\projects\dnspy\dnSpy\Files\Tabs\DefaultDecompileNode.cs:line 28
   at dnSpy.Files.Tabs.FileTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, IFileTreeNodeData node) in C:\projects\dnspy\dnSpy\Files\Tabs\FileTreeNodeDecompiler.cs:line 66
   at dnSpy.Files.Tabs.FileTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, IFileTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\Files\Tabs\FileTreeNodeDecompiler.cs:line 61
   at dnSpy.Files.Tabs.TextEditor.DecompileFileTabContent.AsyncWorker(IShowContext ctx, CancellationTokenSource source) in C:\projects\dnspy\dnSpy\Files\Tabs\TextEditor\DecompileFileTabContent.cs:line 229
   at dnSpy.Files.Tabs.TabContentImpl.<>c__DisplayClass43_1.<ShowInternal>b__0() in C:\projects\dnspy\dnSpy\Files\Tabs\TabContentImpl.cs:line 271
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderExceptionFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.Convert(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at System.Text.DecoderNLS.Convert(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.LinePositionMapper.GetPositionForLine(Int32 line) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 277
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.ReadMembersSection(XmlTextReader reader, LinePositionMapper linePosMapper, List`1 indexList) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 298
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.ReadXmlDoc(XmlTextReader reader) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 241
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider..ctor(String fileName) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 145
   at dnSpy.Shared.Languages.XmlDoc.XmlDocumentationProvider.Create(String fileName) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocumentationProvider.cs:line 117
   at dnSpy.Shared.Languages.XmlDoc.XmlDocLoader.LoadDocumentation(ModuleDef module) in C:\projects\dnspy\dnSpy.Shared\Languages\XmlDoc\XmlDocLoader.cs:line 57
   at dnSpy.Languages.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node) in C:\projects\dnspy\dnSpy.Languages.ILSpy\XmlDoc\AddXmlDocTransform.cs:line 39
   at dnSpy.Languages.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node) in C:\projects\dnspy\dnSpy.Languages.ILSpy\XmlDoc\AddXmlDocTransform.cs:line 51
   at dnSpy.Languages.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node) in C:\projects\dnspy\dnSpy.Languages.ILSpy\XmlDoc\AddXmlDocTransform.cs:line 51
   at dnSpy.Languages.ILSpy.CSharp.CSharpLanguage.AddXmlDocumentation(BuilderState& state, DecompilerSettings settings, AstBuilder astBuilder) in C:\projects\dnspy\dnSpy.Languages.ILSpy\CSharp\CSharpLanguage.cs:line 300
   at dnSpy.Languages.ILSpy.CSharp.CSharpLanguage.Decompile(TypeDef type, ITextOutput output, DecompilationContext ctx) in C:\projects\dnspy\dnSpy.Languages.ILSpy\CSharp\CSharpLanguage.cs:line 280
   at dnSpy.Files.Tabs.NodeDecompiler.Decompile(IFileTreeNodeData node) in C:\projects\dnspy\dnSpy\Files\Tabs\NodeDecompiler.cs:line 92
   at dnSpy.Files.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, IFileTreeNodeData node) in C:\projects\dnspy\dnSpy\Files\Tabs\DefaultDecompileNode.cs:line 28
   at dnSpy.Files.Tabs.FileTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, IFileTreeNodeData node) in C:\projects\dnspy\dnSpy\Files\Tabs\FileTreeNodeDecompiler.cs:line 66
   at dnSpy.Files.Tabs.FileTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, IFileTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\Files\Tabs\FileTreeNodeDecompiler.cs:line 61
   at dnSpy.Files.Tabs.TextEditor.DecompileFileTabContent.AsyncWorker(IShowContext ctx, CancellationTokenSource source) in C:\projects\dnspy\dnSpy\Files\Tabs\TextEditor\DecompileFileTabContent.cs:line 229
   at dnSpy.Files.Tabs.TabContentImpl.<>c__DisplayClass43_1.<ShowInternal>b__0() in C:\projects\dnspy\dnSpy\Files\Tabs\TabContentImpl.cs:line 271
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by 0xd4d** [comment]
Is it a framework assembly? Looks like a bug in the XML doc code.

Which assembly is it and class?

**Comment by gagmeng** [comment]
here are the file
https://www.sendspace.com/file/7qjdyq

**Comment by 0xd4d** [comment]
Could you describe how to reproduce this bug?

**Comment by gagmeng** [comment]
here are the file 
https://www.sendspace.com/file/7qjdyq
Drag the unzipped dll file(Aspose.CAD.dll) within dnspy,  and open any decompile class will cause the error.

**Comment by 0xd4d** [comment]
No, nothing happens, you didn't include the XML doc file(s).

**Comment by gagmeng** [comment]
I don't known why the link is missed in github issues. Attach an image
![qq 20161017132043](https://cloud.githubusercontent.com/assets/13564117/19426139/b56fced2-946c-11e6-9970-f2df5d5d4b51.png)

**Comment by gagmeng** [comment]
here are the file
https://www.sendspace.com/file/7qjdyq
Drag the unzipped dll file(x.dll) within dnspy, and open any decompile class will cause the error.   
I don't known why the link is missed in github issues.


 
 
From: 0xd4d
Date: 2016-10-17 12:30
To: 0xd4d/dnSpy
CC: gagmeng; Author
Subject: Re: [0xd4d/dnSpy] decompiler error (#245)
No, nothing happens, you didn't include the XML doc file(s).
―

**Comment by 0xd4d** [comment]
Since I already have the file, I've removed the link. There's no need to paste the same link again. I'll repost this:

No, nothing happens, you didn't include the XML doc file(s).

**Comment by gagmeng** [comment]
![qq 20161017133040](https://cloud.githubusercontent.com/assets/13564117/19426311/fd271388-946d-11e6-8b0d-be5828552982.png)

**Comment by gagmeng** [comment]
![qq 20161017133355](https://cloud.githubusercontent.com/assets/13564117/19426378/8c422cb0-946e-11e6-9888-11470ddf88db.png)

**Comment by gagmeng** [comment]
here are the Aspose.CAD.xml file
https://www.sendspace.com/file/v649t2
