### ISSUE TITLE
System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#329]
Steps.
After you drag-drop the assembly onto dnSpy (latest devbuild from appveyor location)
and hover mouse over the newly added record in the left tree you'll catch this strange error (which in case is bothering as it  tied to mouse hover over event... and is shown again & again...)

```
---------------------------
dnSpy
---------------------------
System.ArgumentException: Illegal characters in path.

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

   at System.IO.Path.Combine(String path1, String path2)

   at dnSpy.Contracts.Utilities.GacInfo.<GetAssemblies>d__22.MoveNext()

   at dnSpy.Contracts.Utilities.GacInfo.FindInGac(IAssembly asm)

   at dnSpy.Documents.AssemblyResolver.ResolveNormal(IAssembly assembly, ModuleDef sourceModule)

   at dnSpy.Documents.AssemblyResolver.Resolve(IAssembly assembly, ModuleDef sourceModule)

   at dnSpy.Documents.AssemblyResolver.dnlib.DotNet.IAssemblyResolver.Resolve(IAssembly assembly, ModuleDef sourceModule)

   at dnSpy.Decompiler.TargetFrameworkInfo.<GetModules>d__21.MoveNext()

   at dnSpy.Decompiler.TargetFrameworkInfo.GetDotNetVersion2035(ModuleDef module)

   at dnSpy.Decompiler.TargetFrameworkInfo.Create(ModuleDef module)

   at dnSpy.Documents.TreeView.AssemblyDocumentNodeImpl.WriteCore(ITextColorWriter output, IDecompiler decompiler, DocumentNodeWriteOptions options)

   at dnSpy.Contracts.Documents.TreeView.DocumentTreeNodeData.get_ToolTip()

   at dnSpy.Controls.FastTreeNodeView.OnToolTipOpening(ToolTipEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent()

   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

[links removed]

**Comment by 0xd4d** [comment]
Thanks, will have a look at it later. BTW, use three backticks for proper quotes, I updated your comment (click edit to see my change). You can also add eg. C# after it to get C# syntax highlighting.
