### ISSUE TITLE
Node is already used in another tree

### ISSUE THREAD

**Issue by konstantinsp** [0xd4d/dnSpy#426]
Hi, 
i have an error trying to access to whole class and some methods in class.
tried both latest build and latest release of dnspy

![image](https://cloud.githubusercontent.com/assets/3995264/25893755/c9b4ed1c-3581-11e7-85dd-8e38013b2171.png)

```
An error occurred
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Node is already used in another tree.
Parameter name: child
   at ICSharpCode.NRefactory.CSharp.AstNode.AddChild[T](T child, Role`1 role) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\AstNode.cs:line 417
   at ICSharpCode.NRefactory.CSharp.AstNodeCollection`1.AddRange(IEnumerable`1 nodes) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\AstNodeCollection.cs:line 72
   at ICSharpCode.Decompiler.Ast.Transforms.ExpressionTreeConverter.ConvertLambda(InvocationExpression invocation) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ExpressionTreeConverter.cs:line 242
   at ICSharpCode.Decompiler.Ast.Transforms.ExpressionTreeConverter.Convert(Expression expr) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ExpressionTreeConverter.cs:line 129
   at ICSharpCode.Decompiler.Ast.Transforms.ExpressionTreeConverter.TryConvert(DecompilerContext context, Expression expr, StringBuilder sb) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ExpressionTreeConverter.cs:line 48
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 253
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitBlockStatement(BlockStatement blockStatement, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 344
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitBlockStatement(BlockStatement blockStatement, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 344
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 55
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 270
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitTypeDeclaration(TypeDeclaration typeDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 44
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 241
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 29
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 66
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 57
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 188
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Node is already used in another tree.
Parameter name: child
   at ICSharpCode.NRefactory.CSharp.AstNode.AddChild[T](T child, Role`1 role) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\AstNode.cs:line 417
   at ICSharpCode.NRefactory.CSharp.AstNodeCollection`1.AddRange(IEnumerable`1 nodes) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\AstNodeCollection.cs:line 72
   at ICSharpCode.Decompiler.Ast.Transforms.ExpressionTreeConverter.ConvertLambda(InvocationExpression invocation) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ExpressionTreeConverter.cs:line 242
   at ICSharpCode.Decompiler.Ast.Transforms.ExpressionTreeConverter.Convert(Expression expr) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ExpressionTreeConverter.cs:line 129
   at ICSharpCode.Decompiler.Ast.Transforms.ExpressionTreeConverter.TryConvert(DecompilerContext context, Expression expr, StringBuilder sb) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ExpressionTreeConverter.cs:line 48
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 253
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitInvocationExpression(InvocationExpression invocationExpression, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 258
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitBlockStatement(BlockStatement blockStatement, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 344
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitBlockStatement(BlockStatement blockStatement, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 344
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 55
   at ICSharpCode.Decompiler.Ast.Transforms.DelegateConstruction.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DelegateConstruction.cs:line 270
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitTypeDeclaration(TypeDeclaration typeDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 44
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`2.VisitChildren(AstNode node, T data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\DepthFirstAstVisitor.cs:line 1249
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 241
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 29
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 66
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 57
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 188
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

**Comment by 0xd4d** [comment]
How do I reproduce this?

**Comment by konstantinsp** [comment]
![image](https://cloud.githubusercontent.com/assets/3995264/25900986/f98c1a94-359d-11e7-9bd0-aaa849115b06.png)

Here are the dll files that im loading
[BuyerWorkbench.zip](https://github.com/0xd4d/dnSpy/files/989883/BuyerWorkbench.zip)
