### ISSUE TITLE
Value does not fall within the expected range - Error while saving project

### ISSUE THREAD

**Issue by Blizzardo1** [0xd4d/dnSpy#569]
System.ArgumentException: Value does not fall within the expected range.
   at dnlib.DotNet.Pdb.Dss.ISymUnmanagedWriter2.OpenScope(UInt32 startOffset, UInt32& pRetVal)
   at dnlib.DotNet.Pdb.Dss.SymbolWriter.OpenScope(Int32 startOffset) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\Dss\SymbolWriter.cs:line 166
   at dnlib.DotNet.Pdb.PdbWriter.WriteScope(CurrentMethod& info, PdbScope scope, Int32 recursionCounter) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 359
   at dnlib.DotNet.Pdb.PdbWriter.WriteScope(CurrentMethod& info, PdbScope scope, Int32 recursionCounter) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 376
   at dnlib.DotNet.Pdb.PdbWriter.WriteScope(CurrentMethod& info, PdbScope scope, Int32 recursionCounter) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 376
   at dnlib.DotNet.Pdb.PdbWriter.WriteScope(CurrentMethod& info, PdbScope scope, Int32 recursionCounter) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 376
   at dnlib.DotNet.Pdb.PdbWriter.WriteScope(CurrentMethod& info, PdbScope scope, Int32 recursionCounter) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 376
   at dnlib.DotNet.Pdb.PdbWriter.Write(MethodDef method) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 254
   at dnlib.DotNet.Pdb.PdbWriter.Write() in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Pdb\PdbWriter.cs:line 104
   at dnlib.DotNet.Writer.ModuleWriterBase.WritePdbFile() in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 679
   at dnlib.DotNet.Writer.ModuleWriter.WriteFile() in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriter.cs:line 242
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 520
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName) in C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 487
   at dnSpy.AsmEditor.SaveModule.ModuleSaver.SaveAll() in C:\projects\dnspy\Extensions\dnSpy.AsmEditor\SaveModule\ModuleSaver.cs:line 210
   at dnSpy.AsmEditor.SaveModule.SaveMultiModuleVM.SaveAsync(SaveOptionsVM[] mods) in C:\projects\dnspy\Extensions\dnSpy.AsmEditor\SaveModule\SaveMultiModuleVM.cs:line 250

At this point, I'm modifying one line of code in a project, and I get this error. Any reason why this keeps popping up? Is it because I'm in a protected folder even though I'm running as Administrator?

**Comment by 0xd4d** [comment]
Could you email me the assembly and pdb file? My email is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/StartUpClass.cs#L2)

**Comment by 0xd4d** [comment]
No file received, closing it.

**Comment by rolandh** [comment]
Just sent you an email with a repro for this problem

**Comment by 0xd4d** [comment]
Thanks for sending the PDB file. It's now been fixed, it was an old PDB file that shouldn't have been loaded. The assembly had been saved after the PDB file was created.
