### ISSUE TITLE
baml decompile error

### ISSUE THREAD

**Issue by salafsoft** [0xd4d/dnSpy#73]
I have a .exe (which I could upload, but its rather large). In which there are many .baml files in the resources, however each one upon clicking shows:

>An error occurred
System.AggregateException: One or more errors occurred. ---> dnlib.DotNet.TypeResolveException: Could not resolve type: System.Windows.Input.ICommand (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at dnlib.DotNet.Extensions.ResolveThrow(ITypeResolver self, TypeRef typeRef, ModuleDef sourceModule)
   at dnSpy.BamlDecompiler.Baml.KnownThings.InitType(IAssembly assembly, String ns, String name)
   at dnSpy.BamlDecompiler.Baml.KnownThings.InitTypes()
   at dnSpy.BamlDecompiler.Baml.KnownThings..ctor(ModuleDef module)
   at dnSpy.BamlDecompiler.Baml.BamlContext..ctor(ModuleDef module)
   at dnSpy.BamlDecompiler.Baml.BamlContext.ConstructContext(ModuleDef module, BamlDocument document, CancellationToken token)
   at dnSpy.BamlDecompiler.XamlContext.Construct(ModuleDef module, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions)
   at dnSpy.BamlDecompiler.XamlDecompiler.Decompile(ModuleDef module, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions, List`1 assemblyReferences)
   at dnSpy.BamlDecompiler.BamlResourceElementNode.Decompile(ModuleDef module, BamlDocument document, ILanguage lang, ITextOutput output, String& ext, CancellationToken token)
   at dnSpy.BamlDecompiler.BamlResourceElementNode.Decompile(ITextOutput output, CancellationToken token)
   at dnSpy.BamlDecompiler.BamlResourceElementNode.Decompile(IDecompileNodeContext context)
   at dnSpy.Files.Tabs.FileTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, IFileTreeNodeData[] nodes)
   at dnSpy.Files.Tabs.TextEditor.DecompileFileTabContent.AsyncWorker(IFileTabUIContext uiContext, Object userData, CancellationTokenSource source)
   at dnSpy.Files.Tabs.TabContentImpl.<>c__DisplayClass42_1.<ShowInternal>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) dnlib.DotNet.TypeResolveException: Could not resolve type: System.Windows.Input.ICommand (PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at dnlib.DotNet.Extensions.ResolveThrow(ITypeResolver self, TypeRef typeRef, ModuleDef sourceModule)
   at dnSpy.BamlDecompiler.Baml.KnownThings.InitType(IAssembly assembly, String ns, String name)
   at dnSpy.BamlDecompiler.Baml.KnownThings.InitTypes()
   at dnSpy.BamlDecompiler.Baml.KnownThings..ctor(ModuleDef module)
   at dnSpy.BamlDecompiler.Baml.BamlContext..ctor(ModuleDef module)
   at dnSpy.BamlDecompiler.Baml.BamlContext.ConstructContext(ModuleDef module, BamlDocument document, CancellationToken token)
   at dnSpy.BamlDecompiler.XamlContext.Construct(ModuleDef module, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions)
   at dnSpy.BamlDecompiler.XamlDecompiler.Decompile(ModuleDef module, BamlDocument document, CancellationToken token, BamlDecompilerOptions bamlDecompilerOptions, List`1 assemblyReferences)
   at dnSpy.BamlDecompiler.BamlResourceElementNode.Decompile(ModuleDef module, BamlDocument document, ILanguage lang, ITextOutput output, String& ext, CancellationToken token)
   at dnSpy.BamlDecompiler.BamlResourceElementNode.Decompile(ITextOutput output, CancellationToken token)
   at dnSpy.BamlDecompiler.BamlResourceElementNode.Decompile(IDecompileNodeContext context)
   at dnSpy.Files.Tabs.FileTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, IFileTreeNodeData[] nodes)
   at dnSpy.Files.Tabs.TextEditor.DecompileFileTabContent.AsyncWorker(IFileTabUIContext uiContext, Object userData, CancellationTokenSource source)
   at dnSpy.Files.Tabs.TabContentImpl.<>c__DisplayClass42_1.<ShowInternal>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

![image](https://cloud.githubusercontent.com/assets/10601977/12577665/badc6fb2-c413-11e5-9912-f4a2c20c2291.png)

However it works in ILSpy:

![image](https://cloud.githubusercontent.com/assets/10601977/12577680/d5fb56aa-c413-11e5-9e48-6c6e8d3dcc9a.png)

**Comment by 0xd4d** [comment]
You can email me that program, de4dot@gmail.com, and I'll have a look later today or tomorrow.

**Comment by salafsoft** [comment]
Thank you. I have emailed the file. Also not sure if its just this application or others but it behaves strangely when debugging, ie. I would launch it, it hits the break-point, then I would resume. After a while I would identify a place to break-point but it would never hit that again, unless I restarted the application with debugging.

It would be pretty hard for you reproduce this since this application requires a lot of files / installation etc. If you are interested however we could try it.

**Comment by 0xd4d** [comment]
It could possibly  be that the breakpoint is set at an invalid location, eg. where the IL stack isn't empty. If it happens again, switch to IL view and see where the BP is set and paste the surrounding instructions here.

**Comment by salafsoft** [comment]
I have recorded the odd behavior, please see this video:
https://drive.google.com/file/d/0B6N5Vxp6CjC1VHRwbjJka2RDMWc/view?usp=sharing

**Comment by salafsoft** [comment]
IL when not hit:
![il bp not hit](https://cloud.githubusercontent.com/assets/10601977/12579560/bc24be6c-c420-11e5-93f3-3ae74299f31f.PNG)

IL when hit:
![il bp hit](https://cloud.githubusercontent.com/assets/10601977/12579566/d080c856-c420-11e5-84c0-3f855501f8ab.PNG)

**Comment by 0xd4d** [comment]
Could you create a new issue with the BP problem?
