### ISSUE TITLE
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by IamSanjid** [0xd4d/dnSpy#844]
I don't know the problem. I used the latest build from:https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
When I want to open the attached DLL I get this error at
ProtoBuf.Meta->RuntimeTypeModel->WriteSerializers method.
I get this error:
[PSXAPI.zip](https://github.com/0xd4d/dnSpy/files/1992625/PSXAPI.zip)

> An error occurred
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.IsVariableValueUnused(VariableDeclarationStatement varDecl, Statement targetStatement) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 340
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.TransformForeachArrayOrString(ExpressionStatement node) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 735
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitExpressionStatement(ExpressionStatement expressionStatement, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 80
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 58
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 148
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitTypeDeclaration(TypeDeclaration typeDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 45
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 236
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 28
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 67
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 61
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 186
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.IsVariableValueUnused(VariableDeclarationStatement varDecl, Statement targetStatement) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 340
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.TransformForeachArrayOrString(ExpressionStatement node) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 735
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitExpressionStatement(ExpressionStatement expressionStatement, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 80
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 58
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 148
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.ContextTrackingVisitor`1.VisitTypeDeclaration(TypeDeclaration typeDeclaration, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\ContextTrackingVisitor.cs:line 45
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.PatternStatementTransform.VisitChildren(AstNode node, Object data) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\PatternStatementTransform.cs:line 60
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 236
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 28
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.DecompileNode(IDecompileNodeContext context, DocumentTreeNodeData node) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 67
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 61
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in C:\projects\dnspy\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 186
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by 0xd4d** [comment]
Get the latest build (once it's built) and it should fix this bug.

**Comment by IamSanjid** [comment]
Sir, did you mean build myself or I should download from somewhere?

**Comment by 0xd4d** [comment]
No, just use the build server: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
