### ISSUE TITLE
System.OutOfMemoryException when decompiling assembly with huge payload

### ISSUE THREAD

**Issue by AlienHack** [0xd4d/dnSpy#87]
**Edit 1:**

![image](https://cloud.githubusercontent.com/assets/8213866/13167674/094f4924-d708-11e5-97f1-9eb113b10053.png)

I have tried using it with another assembly (small size) and applied the confuserEx (with compressor), dnSpy works. So my assumption is that the problem has occurred when the payload is too huge.

--------

**Original Post:**

Hi I got this error when decompiling confserEx packed assembly

```
	/*
An exception occurred when decompiling this method (06000002)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Int32 <Module>::Main(System.String[])
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ICSharpCode.Decompiler.ILAst.GotoRemoval.RemoveGotos(ILBlock method) in c:\Users\XenoCoreZ\Downloads\dnSpy\dnSpy\ICSharpCode.Decompiler\ILAst\GotoRemoval.cs:line 41
   at ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep) in c:\Users\XenoCoreZ\Downloads\dnSpy\dnSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:line 217
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MemberMapping& mm) in c:\Users\XenoCoreZ\Downloads\dnSpy\dnSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 94
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, MemberMapping& mm) in c:\Users\XenoCoreZ\Downloads\dnSpy\dnSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 68
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, MemberMapping& mm) in c:\Users\XenoCoreZ\Downloads\dnSpy\dnSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 72
   at ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethodBody(MethodDef method, IEnumerable`1 parameters, MemberMapping& mm) in c:\Users\XenoCoreZ\Downloads\dnSpy\dnSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1225
*/;


```

**Comment by AlienHack** [comment]
![image](https://cloud.githubusercontent.com/assets/8213866/13167674/094f4924-d708-11e5-97f1-9eb113b10053.png)

I have tried using it with another confuserEx assembly (with small payload), it seems that the problem has occurred when the payload is too huge,

**Comment by 0xd4d** [comment]
How big is that array in the file that causes OOM?

**Comment by AlienHack** [comment]
It's 3583699 from this sample

![image](https://cloud.githubusercontent.com/assets/8213866/13193983/86d00b2e-d7b5-11e5-9dca-2a69ca3764d7.png)
