### ISSUE TITLE
DecompilerException - Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#870]
Tried with latest build from appveyor. The attached file causes C# decompiler exceptions at

```
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 47
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 383
```

To reproduce add file to dnspy and try to openn for example the method 'CheckUpdate'

[binary.zip](https://github.com/0xd4d/dnSpy/files/2150622/binary.zip)

**Comment by 0xd4d** [comment]
Is it obfuscated?

**Comment by Symbai** [comment]
It looks like it is but other obfuscated binaries I never had a problem with to open (except that it wasnt easy to read)

**Comment by 0xd4d** [comment]
There's no guarantee that the decompiler can handle obfuscated methods. You should deobfuscate it if it fails.

**Comment by XenocodeRCE** [comment]
@Symbai the file you are trying to decompile is using ConfuserEX Antitamper protection.

Attached file with antitamper protection removed.

[Cheat Tool Set___.zip](https://github.com/0xd4d/dnSpy/files/2167551/Cheat.Tool.Set___.zip)

@0xd4d issue can be closed.

**Comment by Symbai** [comment]
@XenocodeRCE Thanks, I tried to follow 0xd4d's suggestions but I'm not good with this and all public tools failed. I'll close the issue then
