### ISSUE TITLE
about build lastest version of dnSpy 2.0

### ISSUE THREAD

**Issue by skypeaful** [0xd4d/dnSpy#93]
I get this error after open dnSpy.exe lastest version build using visual studio 2012
---------------------------
dnSpy
---------------------------
System.Exception: GlyphTypeface does not exists for font 'MS Sans Serif'.

   at ICSharpCode.AvalonEdit.Rendering.GlyphRunFormatter.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Rendering\GlyphRunFormatter.cs:line 107

   at ICSharpCode.AvalonEdit.Rendering.TextView.CalculateDefaultTextMetrics() in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Rendering\TextView.cs:line 1558

   at ICSharpCode.AvalonEdit.Rendering.TextView.OnDocumentChanged(TextDocument oldValue, TextDocument newValue) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Rendering\TextView.cs:line 140

   at ICSharpCode.AvalonEdit.Rendering.TextView.OnDocumentChanged(DependencyObject dp, DependencyPropertyChangedEventArgs e) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Rendering\TextView.cs:line 108

   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at ICSharpCode.AvalonEdit.Rendering.TextView.OnPropertyChanged(DependencyPropertyChangedEventArgs e) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Rendering\TextView.cs:line 2009

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)

   at ICSharpCode.AvalonEdit.Editing.TextArea.OnDocumentChanged(TextDocument oldValue, TextDocument newValue) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Editing\TextArea.cs:line 218

   at ICSharpCode.AvalonEdit.Editing.TextArea.OnDocumentChanged(DependencyObject dp, DependencyPropertyChangedEventArgs e) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Editing\TextArea.cs:line 207

   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at ICSharpCode.AvalonEdit.Editing.TextArea.OnPropertyChanged(DependencyPropertyChangedEventArgs e) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\Editing\TextArea.cs:line 1079

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)

   at ICSharpCode.AvalonEdit.TextEditor.OnDocumentChanged(TextDocument oldValue, TextDocument newValue) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\TextEditor.cs:line 148

   at ICSharpCode.AvalonEdit.TextEditor.OnDocumentChanged(DependencyObject dp, DependencyPropertyChangedEventArgs e) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\TextEditor.cs:line 139

   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)

   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)

   at System.Windows.DependencyObject.SetCurrentValue(DependencyProperty dp, Object value)

   at ICSharpCode.AvalonEdit.TextEditor..ctor(TextArea textArea) in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\TextEditor.cs:line 77

   at ICSharpCode.AvalonEdit.TextEditor..ctor() in d:\dnSpy\AvalonEdit\ICSharpCode.AvalonEdit\TextEditor.cs:line 61

   at dnSpy.TextEditor.NewTextEditor..ctor(IThemeManager themeManager, ITextEditorSettings textEditorSettings) in d:\dnSpy\dnSpy\TextEditor\NewTextEditor.cs:line 195

   at dnSpy.Files.Tabs.TextEditor.TextEditorControl..ctor(IThemeManager themeManager, ToolTipHelper toolTipHelper, ITextEditorSettings textEditorSettings, ITextEditorUIContextImpl uiContext, ITextEditorHelper textEditorHelper, ITextLineObjectManager textLineObjectManager, IImageManager imageManager, IIconBarCommandManager iconBarCommandManager) in d:\dnSpy\dnSpy\Files\Tabs\TextEditor\TextEditorControl.xaml.cs:line 107

   at dnSpy.Files.Tabs.TextEditor.TextEditorUIContextCreator.Create[T]() in d:\dnSpy\dnSpy\Files\Tabs\TextEditor\TextEditorUIContextCreator.cs:line 62

   at dnSpy.Files.Tabs.FileTabUIContextLocator.Create[T]() in d:\dnSpy\dnSpy\Files\Tabs\FileTabUIContextLocator.cs:line 51

   at dnSpy.Files.Tabs.FileTabUIContextLocator.<Get>b__0[T]() in d:\dnSpy\dnSpy\Files\Tabs\FileTabUIContextLocator.cs:line 59

   at dnSpy.Files.Tabs.FileTabUIContextLocator.GetOrCreate[T](Object key, Func`1 creator) in d:\dnSpy\dnSpy\Files\Tabs\FileTabUIContextLocator.cs:line 42

   at dnSpy.Files.Tabs.FileTabUIContextLocator.Get[T]() in d:\dnSpy\dnSpy\Files\Tabs\FileTabUIContextLocator.cs:line 59

   at dnSpy.MainApp.AboutScreenFileTabContent.CreateUIContext(IFileTabUIContextLocator locator) in d:\dnSpy\dnSpy\MainApp\AboutScreen.cs:line 117

   at dnSpy.Files.Tabs.TabContentImpl.ShowInternal(IFileTabContent tabContent, Object serializedUI, Action`1 onShownHandler, Boolean isRefresh) in d:\dnSpy\dnSpy\Files\Tabs\TabContentImpl.cs:line 252

   at dnSpy.Files.Tabs.TabContentImpl.Show(IFileTabContent tabContent, Object serializedUI, Action`1 onShown) in d:\dnSpy\dnSpy\Files\Tabs\TabContentImpl.cs:line 229

   at dnSpy.MainApp.AboutScreenMenuItem.Execute(IMenuItemContext context) in d:\dnSpy\dnSpy\MainApp\AboutScreen.cs:line 84

   at dnSpy.Menus.MenuManager.<>c__DisplayClass11.<Create>b__e(Object a) in d:\dnSpy\dnSpy\Menus\MenuManager.cs:line 372

   at dnSpy.Shared.MVVM.RelayCommand.Execute(Object parameter) in d:\dnSpy\dnSpy.Shared\MVVM\RelayCommand.cs:line 43

   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)

   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------
Please help me how to make it's working properly
Thank

**Comment by 0xd4d** [comment]
Have you tried the latest build from the build server: https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

Also try renaming your `%AppData%\dnSpy\dnSpy.xml` file and start dnSpy.

**Comment by Konctantin** [comment]
You have not updated submodules.

**Comment by skypeaful** [comment]
Thank 0xd4d for help. I deleted %AppData%\dnSpy\dnSpy.xml then everything ok. Maybe dnSpy.xml created by 1.5 is mismatch for 2.0
