### ISSUE TITLE
Unable to attach debugger with Unity (Connect)

### ISSUE THREAD

**Issue by fireundubh** [0xd4d/dnSpy#987]
Version used: x.x.852 (96c6e0c0)

I've been getting these exceptions with recent builds.

```
System.InvalidOperationException: Couldn't open process 8756
   at dnSpy.Debugger.Impl.DbgProcessImpl..ctor(DbgManagerImpl owner, Dispatcher dispatcher, Int32 pid, DbgProcessState state, Boolean shouldDetach) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Impl\DbgProcessImpl.cs:line 149
   at dnSpy.Debugger.Impl.DbgManagerImpl.GetOrCreateProcess_DbgThread(Int32 pid, DbgStartKind startKind, Boolean& createdProcess) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Impl\DbgManagerImpl.cs:line 363
   at dnSpy.Debugger.Impl.DbgManagerImpl.OnConnected_DbgThread(DbgEngine engine, DbgMessageConnected e) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Impl\DbgManagerImpl.cs:line 426
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at dnSpy.Debugger.Impl.DebuggerThread.DebuggerThreadProc(AutoResetEvent autoResetEvent) in C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Impl\DebuggerThread.cs:line 62
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

If I switch to a slightly older build (697ab191), I _can_ attach the debugger via Unity (Connect), but - and maybe this isn't a dnSpy problem - breakpoint tooltips always indicate:

> The breakpoint will not currently be hit. The module hasn't been loaded or no symbols have been loaded for this module.

I'll try an even older build a bit later when I have some time.

**Comment by fireundubh** [comment]
Well, I rebooted Windows 10 and fixed a weird issue with a monkey patcher that I can't even describe. I tried running the latest build again and was able to attach the debugger; however, the breakpoint tooltips still indicate set breakpoints won't be hit.

**Comment by 0xd4d** [comment]
Make sure you set BPs in the correct module. Open it from the Modules window. You'll also see that message if the module hasn't been loaded yet, so wait until some code really needs it loaded.

**Comment by 0xd4d** [comment]
Seems like it fixed itself after rebooting your computer, so I'm closing this. The BP issue is most likely because the module hasn't been loaded by the CLR yet.
